# Generated by Django 3.2.13 on 2022-06-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_auto_20220616_2106"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blogapp.category",
            ),
            preserve_default=False,
        ),
    ]
