# Generated by Django 3.2.13 on 2022-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("intro", models.TextField()),
                ("body", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
